2023-06-13 14:28:56,640 INFO    MainThread:517 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:28:56,641 INFO    MainThread:517 [wandb_setup.py:_flush():76] Configure stats pid to 517
2023-06-13 14:28:56,641 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:28:56,641 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:28:56,641 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:28:56,642 INFO    MainThread:517 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:28:56,642 INFO    MainThread:517 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-13 14:28:56,643 INFO    MainThread:517 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_142856-4ko5bakt/logs/debug.log
2023-06-13 14:28:56,643 INFO    MainThread:517 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_142856-4ko5bakt/logs/debug-internal.log
2023-06-13 14:28:56,643 INFO    MainThread:517 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f01d1704970>
2023-06-13 14:28:56,644 INFO    MainThread:517 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:28:56,644 INFO    MainThread:517 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:28:56,644 INFO    MainThread:517 [wandb_init.py:init():571] re-initializing run, found existing run on stack: vsn6k5uf
2023-06-13 14:28:56,647 INFO    MainThread:517 [wandb_run.py:_finish():1890] finishing run pringlesinghal/shapley-fl/vsn6k5uf
2023-06-13 14:28:56,649 INFO    MainThread:517 [wandb_run.py:_atexit_cleanup():2124] got exitcode: 0
2023-06-13 14:28:56,650 INFO    MainThread:517 [wandb_run.py:_restore():2107] restore
2023-06-13 14:28:56,650 INFO    MainThread:517 [wandb_run.py:_restore():2113] restore done
2023-06-13 14:31:25,800 WARNING MsgRouterThr:517 [router.py:message_loop():77] message_loop has been closed
2023-06-13 14:31:32,685 INFO    MainThread:517 [wandb_run.py:_restore():2107] restore
2023-06-13 14:31:32,686 INFO    MainThread:517 [wandb_run.py:_restore():2113] restore done
2023-06-13 14:31:32,787 ERROR   MainThread:517 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2133, in _atexit_cleanup
    self._on_finish()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2372, in _on_finish
    _ = exit_handle.wait(timeout=-1, on_progress=self._on_progress_exit)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 298, in wait
    on_probe(probe_handle)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2337, in _on_probe_exit
    result = handle.wait(timeout=0)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 581, in init
    latest_run.finish()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1881, in finish
    return self._finish(exit_code, quiet)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1896, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 2144, in _atexit_cleanup
    self._backend.cleanup()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/backend/backend.py", line 255, in cleanup
    self.interface.join()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 638, in join
    super().join()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface.py", line 742, in join
    _ = self._communicate_shutdown()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 551, in _communicate_shutdown
    _ = self._communicate(record)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_shared.py", line 285, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/interface_sock.py", line 60, in _communicate_async
    future = self._router.send_and_receive(rec, local=local)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/router.py", line 94, in send_and_receive
    self._send_message(rec)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/interface/router_sock.py", line 36, in _send_message
    self._sock_client.send_record_communicate(record)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 216, in send_record_communicate
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-06-13 14:34:32,744 INFO    MainThread:517 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:34:32,745 INFO    MainThread:517 [wandb_setup.py:_flush():76] Configure stats pid to 517
2023-06-13 14:34:32,745 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:34:32,746 INFO    MainThread:517 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:34:32,747 INFO    MainThread:517 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2023-06-13 14:34:32,748 INFO    MainThread:517 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143432-qkb6i4ar/logs/debug.log
2023-06-13 14:34:32,748 INFO    MainThread:517 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143432-qkb6i4ar/logs/debug-internal.log
2023-06-13 14:34:32,749 INFO    MainThread:517 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:34:32,749 INFO    MainThread:517 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:34:32,750 INFO    MainThread:517 [wandb_init.py:init():571] re-initializing run, found existing run on stack: vsn6k5uf
2023-06-13 14:34:32,752 INFO    MainThread:517 [wandb_run.py:_finish():1890] finishing run pringlesinghal/shapley-fl/vsn6k5uf
2023-06-13 14:34:32,844 ERROR   MainThread:517 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 581, in init
    latest_run.finish()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1881, in finish
    return self._finish(exit_code, quiet)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_run.py", line 1909, in _finish
    manager._inform_finish(run_id=self._run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 224, in _inform_finish
    svc_iface._svc_inform_finish(run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 54, in _svc_inform_finish
    self._sock_client.send(inform_finish=inform_finish)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
