2023-06-13 14:38:26,034 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:38:26,034 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:38:26,035 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:38:26,035 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:38:26,035 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:38:26,035 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:38:26,036 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143825-cpixy1gj/logs/debug.log
2023-06-13 14:38:26,036 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143825-cpixy1gj/logs/debug-internal.log
2023-06-13 14:38:26,037 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:38:26,037 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'client-transmission', 'shapley_threshold': 0.5, 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'shapley'}
2023-06-13 14:38:26,037 INFO    MainThread:19897 [wandb_init.py:init():571] re-initializing run, found existing run on stack: mj3axrtb
2023-06-13 14:38:26,041 INFO    MainThread:19897 [wandb_run.py:_finish():1890] finishing run pringlesinghal/shapley-fl/mj3axrtb
2023-06-13 14:38:26,042 INFO    MainThread:19897 [jupyter.py:save_history():445] not saving jupyter history
2023-06-13 14:38:26,042 INFO    MainThread:19897 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-13 14:38:26,043 INFO    MainThread:19897 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-06-13 14:38:26,043 INFO    MainThread:19897 [wandb_run.py:_atexit_cleanup():2124] got exitcode: 0
2023-06-13 14:38:26,044 INFO    MainThread:19897 [wandb_run.py:_restore():2107] restore
2023-06-13 14:38:26,044 INFO    MainThread:19897 [wandb_run.py:_restore():2113] restore done
2023-06-13 14:39:31,278 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:39:31,281 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:39:31,299 INFO    MainThread:19897 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-13 14:39:31,323 INFO    MainThread:19897 [wandb_init.py:init():606] backend started and connected
2023-06-13 14:39:31,364 INFO    MainThread:19897 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-06-13 14:39:32,200 INFO    MainThread:19897 [wandb_init.py:init():703] updated telemetry
2023-06-13 14:39:32,230 INFO    MainThread:19897 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-13 14:39:39,122 WARNING MainThread:19897 [wandb_init.py:init():1174] interrupted
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 739, in init
    result = run_init_handle.wait(
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/usr/lib/python3.10/threading.py", line 607, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.10/threading.py", line 324, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2023-06-13 14:39:53,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:39:53,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:39:53,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:39:53,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:39:53,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:39:53,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:39:53,693 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143953-o552nmmm/logs/debug.log
2023-06-13 14:39:53,694 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_143953-o552nmmm/logs/debug-internal.log
2023-06-13 14:39:53,694 INFO    MainThread:19897 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fb3f26a1930>
2023-06-13 14:39:53,694 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:39:53,695 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'client-transmission', 'shapley_threshold': 0.5, 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'shapley'}
2023-06-13 14:39:53,695 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:39:53,695 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:39:53,700 INFO    MainThread:19897 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-13 14:39:53,706 INFO    MainThread:19897 [wandb_init.py:init():606] backend started and connected
2023-06-13 14:39:53,721 INFO    MainThread:19897 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-06-13 14:39:55,081 INFO    MainThread:19897 [wandb_init.py:init():703] updated telemetry
2023-06-13 14:39:55,112 INFO    MainThread:19897 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-13 14:40:55,162 ERROR   MainThread:19897 [wandb_init.py:init():762] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-13 14:40:55,248 ERROR   MainThread:19897 [wandb_init.py:init():1170] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-13 14:40:58,724 WARNING MsgRouterThr:19897 [router.py:message_loop():77] message_loop has been closed
2023-06-13 14:40:58,725 WARNING MsgRouterThr:19897 [router.py:message_loop():77] message_loop has been closed
2023-06-13 14:40:58,725 WARNING MsgRouterThr:19897 [router.py:message_loop():77] message_loop has been closed
2023-06-13 14:42:50,549 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:42:50,551 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:42:50,551 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144250-usvn1dd0/logs/debug.log
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144250-usvn1dd0/logs/debug-internal.log
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:42:50,553 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:42:50,553 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:42:50,660 ERROR   MainThread:19897 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-06-13 14:43:21,689 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:43:21,690 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:43:21,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:43:21,693 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144321-6oazszai/logs/debug.log
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144321-6oazszai/logs/debug-internal.log
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:43:21,695 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:43:21,695 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:43:21,793 ERROR   MainThread:19897 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
