2023-06-13 14:42:50,549 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:42:50,550 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:42:50,551 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:42:50,551 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144250-usvn1dd0/logs/debug.log
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144250-usvn1dd0/logs/debug-internal.log
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:42:50,552 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:42:50,553 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:42:50,553 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:42:50,660 ERROR   MainThread:19897 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-06-13 14:43:21,689 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-13 14:43:21,690 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Configure stats pid to 19897
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /root/.config/wandb/settings
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/settings
2023-06-13 14:43:21,691 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-13 14:43:21,692 INFO    MainThread:19897 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-13 14:43:21,693 INFO    MainThread:19897 [wandb_init.py:_log_setup():507] Logging user logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144321-6oazszai/logs/debug.log
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:_log_setup():508] Logging internal logs to /content/gdrive/MyDrive/AAU_Project/Goal_Oriented_Federated_Learning/wandb/run-20230613_144321-6oazszai/logs/debug-internal.log
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:init():547] calling init triggers
2023-06-13 14:43:21,694 INFO    MainThread:19897 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'random_seed': 0, 'num_clients': 20, 'alpha': 1000000.0, 'learning_rate': 0.001, 'num_communication_rounds': 400, 'server_select_fraction': 0.5, 'client_iterations': 1, 'experiment': 'random', 'server_selection': 'random', 'client_sampling': 'random', 'client_transmission': 'always'}
2023-06-13 14:43:21,695 INFO    MainThread:19897 [wandb_init.py:init():596] starting backend
2023-06-13 14:43:21,695 INFO    MainThread:19897 [wandb_init.py:init():600] setting up manager
2023-06-13 14:43:21,793 ERROR   MainThread:19897 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
